# Generated by Django 4.2.7 on 2023-11-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('BT', 'Butter'), ('CZ', 'Cheese'), ('IC', 'Ice Creams'), ('GH', 'Ghee'), ('LS', 'Lassi')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product'),
        ),
    ]
