# Generated by Django 4.2.7 on 2023-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_item_category_item_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product_image',
        ),
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/003/170/825/original/isolated-food-plate-fork-and-spoon-design-free-vector.jpg', max_length=500),
        ),
    ]
